export default {
  UPDATE_DRAGGING_CARD: 'UPDATE_DRAGGING_CARD',
  SET_REMOVED_ITEM: 'SET_REMOVED_INDEX',
  SET_ADDED_ITEM: 'SET_ADDED_INDEX',
  RESET_ITEMS: 'RESET_ITEMS',
  COMPLETE_MOVE: 'COMPLETE_MOVE',
  UPLOAD_CARDS: 'UPLOAD_CARDS',
  ADD_NEW_CARD: 'ADD_NEW_CARD',
  DELETE_CARD: 'DELETE_CARD',
};